[atm_init]
# ccpp suites
ccpp_suite_regional_init=FV3_HAFS_v1_thompson_c3
ccpp_suite_glob_init=FV3_HAFS_v1_thompson_c3
ccpp_suite_nest_init=FV3_HAFS_v1_thompson_c3

[forecast]
# ccpp suites
ccpp_suite_regional=FV3_HAFS_v1_thompson_nonsst_c3
ccpp_suite_glob=FV3_HAFS_v1_thompson_nonsst_c3
ccpp_suite_nest=FV3_HAFS_v1_thompson_nonsst_c3

imfshalcnv=5
imfdeepcnv=5

dt_inner={dt_atmos}
